### PR TITLE
Windows support

### LINKED ISSUE #132: Support Windows runners
**Is your feature request related to a problem? Please describe.**
Swift 5.3 is now available on Windows, so it would be great to use this action to install the Swift toolchain on Windows hosts.

**Describe the solution you'd like**
I would like to be able to use this action with Windows runners.

### PR DESCRIPTION
**Pull request by fwal**
Adds support for windows runners.

- [x] Resolve correct version
- [x] Download Swift package
- [ ] Setup Swift on windows 
- [ ] GPG signature validation
- [ ] Tests

Fixes #132.

## Help wanted!

As I have limited experience from and access to a windows environment I could benefit from additional help.
Currently I'm trying to figure out how to run commands in the "VS2019 Command Prompt" as required by the toolchain.
Any help in this area would be greatly appreciated!

### CODE REVIEW

**Comment by Zialus** [comment]
Some Relevant information [here](https://github.com/kylef/swiftenv/issues/180#issuecomment-703281035)

**Comment by doozMen** [comment]
I made a test on windows and I thing we should wait unfortunately swift ton windows does not yet support spm. But I would be glad to help. Keep up the good work!

**Comment by fwal** [comment]
Hi @doozMen!

Yeah it also seems like the installer requires the use of a GUI which is a no-go on CI but hopefully this will change soon. 

Thanks for trying!

**Comment by compnerd** [comment]
@fwal it shouldn't.  I've been using the installer on GH Actions for a while now with automated installations: https://github.com/compnerd/swift-win32/blob/main/.github/workflows/windows.yml

**Comment by fwal** [comment]
@compnerd That's great news and thank you for the example action, that helps a lot! 🎉

**Comment by MaxDesiatov** [comment]
I wonder if there's an easy way to call into PowerShell from TypeScript in the code action, or to make it composite only on Windows? I've created a separate action specifically for Windows, and I wonder if your action could maybe use mine as a step somehow? https://github.com/MaxDesiatov/swift-windows-action

**Comment by fwal** [comment]
Closed in favour of https://github.com/swift-actions/setup-swift/pull/424 🎉

**Pull request closed without merging**
