### PR TITLE
Add Windows support

### LINKED ISSUE #132: Support Windows runners
**Is your feature request related to a problem? Please describe.**
Swift 5.3 is now available on Windows, so it would be great to use this action to install the Swift toolchain on Windows hosts.

**Describe the solution you'd like**
I would like to be able to use this action with Windows runners.

### PR DESCRIPTION
**Pull request by soumyamahunt**
This PR works on top of #140, to provide Windows runner support.

Tasks completed by @fwal in #140:
- [x] Resolve correct version
- [x] Download Swift package

Tasks completed in this PR:
- [x] Setup Swift on windows
- [x] GPG signature validation
- [x] Tests

Fixes #132.

### CODE REVIEW

**Comment by soumyamahunt** [comment]
@slashmo @fwal I have made changes for windows setup actions as mentioned in the docs, please review and let me know if any further changes needed.

**Comment by fwal** [comment]
Hi @soumyamahunt! 👋🏻 

Thanks for your contribution, this looks great!
Could you remove any changes made in the `dist` folder? We let GitHub actions and manual builds manage that.

**Comment by soumyamahunt** [comment]
> Hi @soumyamahunt! 👋🏻
> 
> Thanks for your contribution, this looks great! Could you remove any changes made in the `dist` folder? We let GitHub actions and manual builds manage that.

Hi @fwal, the changes to the `dist` folder are auto-generated and shouldn't impact the action. I pushed these changes since I am using this branch in my swift-package jobs until swift-actions creates a new release with windows support. Removing these changes will break those jobs.

**Comment by fwal** [comment]
@soumyamahunt This is due to security concerns, I would rather not have the dist folder checked in at all but that's just how actions work 😅 I'll sanitise in another branch and merge this in!

**Pull request merged**
