### PR TITLE
Add swift 5.7 support

### PR DESCRIPTION
**Pull request by rizwankce**

### CODE REVIEW

**Comment by fwal** [comment]
Fixes #446

**Review by fwal — APPROVED** [review]

**Review by fwal — APPROVED** [review]

**Comment by fwal** [comment]
Thanks for the contribution @rizwankce! 🎉  I had to make some tweaks but will roll out the new version in a moment.

**Comment by fumoboy007** [comment]
Hi, how come we are excluding Swift 5.7+ from Windows workflows?

**Comment by fumoboy007** [comment]
> Hi, how come we are excluding Swift 5.7+ from Windows workflows?

@fwal @rizwankce ^

**Pull request merged**
